CREATE VIEW VISTA_CONSOLIDADO AS
SELECT
    CASE
        WHEN p1.LOCALIDAD_CALCULADA = '01' THEN 'Usaquén'
        WHEN p1.LOCALIDAD_CALCULADA = '02' THEN 'Chapinero'
        WHEN p1.LOCALIDAD_CALCULADA = '03' THEN 'Santa Fe'
        WHEN p1.LOCALIDAD_CALCULADA = '04' THEN 'San Cristóbal'
        WHEN p1.LOCALIDAD_CALCULADA = '05' THEN 'Usme'
        WHEN p1.LOCALIDAD_CALCULADA = '06' THEN 'Tunjuelito'
        WHEN p1.LOCALIDAD_CALCULADA = '07' THEN 'Bosa'
        WHEN p1.LOCALIDAD_CALCULADA = '08' THEN 'Kennedy'
        WHEN p1.LOCALIDAD_CALCULADA = '09' THEN 'Fontibón'
        WHEN p1.LOCALIDAD_CALCULADA = '10' THEN 'Engativá'
        WHEN p1.LOCALIDAD_CALCULADA = '11' THEN 'Suba'
        WHEN p1.LOCALIDAD_CALCULADA = '12' THEN 'Barrios Unidos'
        WHEN p1.LOCALIDAD_CALCULADA = '13' THEN 'Teusaquillo'
        WHEN p1.LOCALIDAD_CALCULADA = '14' THEN 'Los Mártires'
        WHEN p1.LOCALIDAD_CALCULADA = '15' THEN 'Antonio Nariño'
        WHEN p1.LOCALIDAD_CALCULADA = '16' THEN 'Puente Aranda'
        WHEN p1.LOCALIDAD_CALCULADA = '17' THEN 'La Candelaria'
        WHEN p1.LOCALIDAD_CALCULADA = '18' THEN 'Rafael Uribe Uribe'
        WHEN p1.LOCALIDAD_CALCULADA = '19' THEN 'Ciudad Bolívar'
        WHEN p1.LOCALIDAD_CALCULADA = '20' THEN 'Sumapaz'
        ELSE 'Localidad Desconocida'
    END AS Localidad,
    p1.SEXO AS Sexo,
    TIMESTAMPDIFF(YEAR, p1.FECHA_DE_NACIMIENTO_USUARIO, CURDATE()) AS Edad,
    'PROGRAMA 1' AS Programa,
    CASE
        WHEN p1.ASEGURADOR = 'CAPITAL SALUD E.P.S.' THEN 'CAPITAL SALUD E.P.S.'
        WHEN p1.ASEGURADOR = 'NUEVA EPS S.A' THEN 'NUEVA EPS S.A'
        WHEN p1.ASEGURADOR = 'SALUD TOTAL S.A.' THEN 'SALUD TOTAL S.A.'
        WHEN p1.ASEGURADOR = 'EPS Y MEDICINA PREPAGADA SURAMERICANA S.A' THEN 'EPS Y MEDICINA PREPAGADA SURAMERICANA S.A'
        WHEN p1.ASEGURADOR = 'FERROCARRILES NACIONAL E.P.S.' THEN 'FERROCARRILES NACIONAL E.P.S.'
        WHEN p1.ASEGURADOR = 'SALUD BOLÍVAR E.P.S.' THEN 'SALUD BOLÍVAR E.P.S.'
        WHEN p1.ASEGURADOR = 'COMPENSAR E.P.S.' THEN 'COMPENSAR E.P.S.'
        WHEN p1.ASEGURADOR = 'E.P.S. SANITAS' THEN 'E.P.S. SANITAS'
        WHEN p1.ASEGURADOR = 'FAMISANAR E.P.S. LTDA - CAFAM - COLSUBSIDIO' THEN 'FAMISANAR E.P.S. LTDA - CAFAM - COLSUBSIDIO'
        WHEN p1.ASEGURADOR = 'ALIANSALUD E.P.S.' THEN 'ALIANSALUD E.P.S.'
        WHEN p1.ASEGURADOR = 'COOSALUD E.P.S.' THEN 'COOSALUD E.P.S.'
        WHEN p1.ASEGURADOR = 'SOS E.P.S.' THEN 'SOS E.P.S.'
        WHEN p1.ASEGURADOR = 'MALLAMAS E.P.S.' THEN 'MALLAMAS E.P.S.'
        WHEN p1.ASEGURADOR = 'SIN DATO' THEN 'SIN DATO'
        WHEN p1.ASEGURADOR = 'SIN ASEGURAMIENTO' THEN 'SIN ASEGURAMIENTO'
        ELSE 'OTROS'
    END AS EAPB,
    p1.FECHA_DE_LA_CONSULTA AS FechaCaracterizacion
FROM programa1 AS p1

UNION ALL

SELECT
    CASE
        WHEN p2.LOCALIDAD = '01' THEN 'Usaquén'
        WHEN p2.LOCALIDAD = '02' THEN 'Chapinero'
        WHEN p2.LOCALIDAD = '03' THEN 'Santa Fe'
        WHEN p2.LOCALIDAD = '04' THEN 'San Cristóbal'
        WHEN p2.LOCALIDAD = '05' THEN 'Usme'
        WHEN p2.LOCALIDAD = '06' THEN 'Tunjuelito'
        WHEN p2.LOCALIDAD = '07' THEN 'Bosa'
        WHEN p2.LOCALIDAD = '08' THEN 'Kennedy'
        WHEN p2.LOCALIDAD = '09' THEN 'Fontibón'
        WHEN p2.LOCALIDAD = '10' THEN 'Engativá'
        WHEN p2.LOCALIDAD = '11' THEN 'Suba'
        WHEN p2.LOCALIDAD = '12' THEN 'Barrios Unidos'
        WHEN p2.LOCALIDAD = '13' THEN 'Teusaquillo'
        WHEN p2.LOCALIDAD = '14' THEN 'Los Mártires'
        WHEN p2.LOCALIDAD = '15' THEN 'Antonio Nariño'
        WHEN p2.LOCALIDAD = '16' THEN 'Puente Aranda'
        WHEN p2.LOCALIDAD = '17' THEN 'La Candelaria'
        WHEN p2.LOCALIDAD = '18' THEN 'Rafael Uribe Uribe'
        WHEN p2.LOCALIDAD = '19' THEN 'Ciudad Bolívar'
        WHEN p2.LOCALIDAD = '20' THEN 'Sumapaz'
        ELSE 'Localidad Desconocida'
    END,
    p2.SEXO_BIOLOGICO AS Sexo,
    TIMESTAMPDIFF(YEAR, p2.FECHA_DE_NACIMIENTO, CURDATE()) AS Edad,
    'PROGRAMA 2' AS Programa,
    CASE
        WHEN p2.EAPB = 'CAPITAL SALUD E.P.S.' THEN 'CAPITAL SALUD E.P.S.'
        WHEN p2.EAPB = 'NUEVA EPS S.A' THEN 'NUEVA EPS S.A'
        WHEN p2.EAPB = 'SALUD TOTAL S.A.' THEN 'SALUD TOTAL S.A.'
        WHEN p2.EAPB = 'EPS Y MEDICINA PREPAGADA SURAMERICANA S.A' THEN 'EPS Y MEDICINA PREPAGADA SURAMERICANA S.A'
        WHEN p2.EAPB = 'FERROCARRILES NACIONAL E.P.S.' THEN 'FERROCARRILES NACIONAL E.P.S.'
        WHEN p2.EAPB = 'SALUD BOLÍVAR E.P.S.' THEN 'SALUD BOLÍVAR E.P.S.'
        WHEN p2.EAPB = 'COMPENSAR E.P.S.' THEN 'COMPENSAR E.P.S.'
        WHEN p2.EAPB = 'E.P.S. SANITAS' THEN 'E.P.S. SANITAS'
        WHEN p2.EAPB = 'FAMISANAR E.P.S. LTDA - CAFAM - COLSUBSIDIO' THEN 'FAMISANAR E.P.S. LTDA - CAFAM - COLSUBSIDIO'
        WHEN p2.EAPB = 'ALIANSALUD E.P.S.' THEN 'ALIANSALUD E.P.S.'
        WHEN p2.EAPB = 'COOSALUD E.P.S.' THEN 'COOSALUD E.P.S.'
        WHEN p2.EAPB = 'SOS E.P.S.' THEN 'SOS E.P.S.'
        WHEN p2.EAPB = 'MALLAMAS E.P.S.' THEN 'MALLAMAS E.P.S.'
        WHEN p2.EAPB = 'SIN DATO' THEN 'SIN DATO'
        WHEN p2.EAPB = 'SIN ASEGURAMIENTO' THEN 'SIN ASEGURAMIENTO'
        ELSE 'OTROS'
    END,
    p2.FECHA_DE_LA_CONSULTA
FROM programa2 AS p2

UNION ALL

SELECT
    CASE
        WHEN p3.LOCALIDADFIC_3 = '01' THEN 'Usaquén'
        WHEN p3.LOCALIDADFIC_3 = '02' THEN 'Chapinero'
        WHEN p3.LOCALIDADFIC_3 = '03' THEN 'Santa Fe'
        WHEN p3.LOCALIDADFIC_3 = '04' THEN 'San Cristóbal'
        WHEN p3.LOCALIDADFIC_3 = '05' THEN 'Usme'
        WHEN p3.LOCALIDADFIC_3 = '06' THEN 'Tunjuelito'
        WHEN p3.LOCALIDADFIC_3 = '07' THEN 'Bosa'
        WHEN p3.LOCALIDADFIC_3 = '08' THEN 'Kennedy'
        WHEN p3.LOCALIDADFIC_3 = '09' THEN 'Fontibón'
        WHEN p3.LOCALIDADFIC_3 = '10' THEN 'Engativá'
        WHEN p3.LOCALIDADFIC_3 = '11' THEN 'Suba'
        WHEN p3.LOCALIDADFIC_3 = '12' THEN 'Barrios Unidos'
        WHEN p3.LOCALIDADFIC_3 = '13' THEN 'Teusaquillo'
        WHEN p3.LOCALIDADFIC_3 = '14' THEN 'Los Mártires'
        WHEN p3.LOCALIDADFIC_3 = '15' THEN 'Antonio Nariño'
        WHEN p3.LOCALIDADFIC_3 = '16' THEN 'Puente Aranda'
        WHEN p3.LOCALIDADFIC_3 = '17' THEN 'La Candelaria'
        WHEN p3.LOCALIDADFIC_3 = '18' THEN 'Rafael Uribe Uribe'
        WHEN p3.LOCALIDADFIC_3 = '19' THEN 'Ciudad Bolívar'
        WHEN p3.LOCALIDADFIC_3 = '20' THEN 'Sumapaz'
        ELSE 'Localidad Desconocida'
    END,
    p3.GENERO AS Sexo,
    TIMESTAMPDIFF(YEAR, p3.NACIMIENTO, CURDATE()) AS Edad,
    'PROGRAMA 3' AS Programa,
    CASE
        WHEN p3.EAPB = 'CAPITAL SALUD E.P.S.' THEN 'CAPITAL SALUD E.P.S.'
        WHEN p3.EAPB = 'NUEVA EPS S.A' THEN 'NUEVA EPS S.A'
        WHEN p3.EAPB = 'SALUD TOTAL S.A.' THEN 'SALUD TOTAL S.A.'
        WHEN p3.EAPB = 'EPS Y MEDICINA PREPAGADA SURAMERICANA S.A' THEN 'EPS Y MEDICINA PREPAGADA SURAMERICANA S.A'
        WHEN p3.EAPB = 'FERROCARRILES NACIONAL E.P.S.' THEN 'FERROCARRILES NACIONAL E.P.S.'
        WHEN p3.EAPB = 'SALUD BOLÍVAR E.P.S.' THEN 'SALUD BOLÍVAR E.P.S.'
        WHEN p3.EAPB = 'COMPENSAR E.P.S.' THEN 'COMPENSAR E.P.S.'
        WHEN p3.EAPB = 'E.P.S. SANITAS' THEN 'E.P.S. SANITAS'
        WHEN p3.EAPB = 'FAMISANAR E.P.S. LTDA - CAFAM - COLSUBSIDIO' THEN 'FAMISANAR E.P.S. LTDA - CAFAM - COLSUBSIDIO'
        WHEN p3.EAPB = 'ALIANSALUD E.P.S.' THEN 'ALIANSALUD E.P.S.'
        WHEN p3.EAPB = 'COOSALUD E.P.S.' THEN 'COOSALUD E.P.S.'
        WHEN p3.EAPB = 'SOS E.P.S.' THEN 'SOS E.P.S.'
        WHEN p3.EAPB = 'MALLAMAS E.P.S.' THEN 'MALLAMAS E.P.S.'
        WHEN p3.EAPB = 'SIN DATO' THEN 'SIN DATO'
        WHEN p3.EAPB = 'SIN ASEGURAMIENTO' THEN 'SIN ASEGURAMIENTO'
        ELSE 'OTROS'
    END,
    p3.FECHA_CONSULTA
FROM programa3 AS p3
